import _ from 'lodash'
import { defineConfig, type Options } from 'tsup'

const sharedConfig: Options = {
  dts: true,
  format: ['cjs', 'esm', 'iife'],
  publicDir: 'public',
  splitting: false,
}

export default defineConfig((options): Options => ({
  ...sharedConfig,
  clean: !options.watch, // only clean once when not watching
  minify: !options.watch,
  entry: [
    'lib/index.ts',
    'lib/crc8.ts',
    'lib/crc8autosar.ts',
    'lib/crc8bluetooth.ts',
    'lib/crc8cardx.ts',
    'lib/crc8cdma2000.ts',
    'lib/crc8darc.ts',
    'lib/crc8dvbs2.ts',
    'lib/crc8ebu.ts',
    'lib/crc8gsma.ts',
    'lib/crc8gsmb.ts',
    'lib/crc8hitag.ts',
    'lib/crc8icode.ts',
    'lib/crc8itu.ts',
    'lib/crc8legic.ts',
    'lib/crc8mad.ts',
    'lib/crc8maxim.ts',
    'lib/crc8nrsc5.ts',
    'lib/crc8opensafety.ts',
    'lib/crc8rohc.ts',
    'lib/crc8saej1850.ts',
    'lib/crc8wcdma.ts',
    'lib/crc16a.ts',
    'lib/crc16arc.ts',
    'lib/crc16augccitt.ts',
    'lib/crc16buypass.ts',
    'lib/crc16ccittfalse.ts',
    'lib/crc16cdma2000.ts',
    'lib/crc16cms.ts',
    'lib/crc16dds110.ts',
    'lib/crc16dectr.ts',
    'lib/crc16dectx.ts',
    'lib/crc16dnp.ts',
    'lib/crc16en13757.ts',
    'lib/crc16genibus.ts',
    'lib/crc16gsm.ts',
    'lib/crc16iclass.ts',
    'lib/crc16kermit.ts',
    'lib/crc16lj1200.ts',
    'lib/crc16m17.ts',
    'lib/crc16maxim.ts',
    'lib/crc16mcrf4xx.ts',
    'lib/crc16modbus.ts',
    'lib/crc16nrsc5.ts',
    'lib/crc16opensafetya.ts',
    'lib/crc16opensafetyb.ts',
    'lib/crc16philips.ts',
    'lib/crc16profibus.ts',
    'lib/crc16riello.ts',
    'lib/crc16t10dif.ts',
    'lib/crc16teledisk.ts',
    'lib/crc16tms37157.ts',
    'lib/crc16usb.ts',
    'lib/crc16x25.ts',
    'lib/crc16xmodem.ts',
    'lib/crc32.ts',
    'lib/crc32autosar.ts',
    'lib/crc32bzip2.ts',
    'lib/crc32c.ts',
    'lib/crc32cdromedc.ts',
    'lib/crc32d.ts',
    'lib/crc32jamcrc.ts',
    'lib/crc32mef.ts',
    'lib/crc32mpeg2.ts',
    'lib/crc32posix.ts',
    'lib/crc32q.ts',
    'lib/crc32sata.ts',
    'lib/crc32xfer.ts',
    'lib/genericCrc8.ts',
    'lib/genericCrc16.ts',
    'lib/genericCrc32.ts',
  ],
}))
