import _ from 'lodash'
import { defineConfig, type Options } from 'tsup'

const sharedConfig: Options = {
  dts: true,
  format: ['cjs', 'esm', 'iife'],
  publicDir: 'public',
  splitting: false,
}

export default defineConfig((options): Options[] => [
  {
    ...sharedConfig,
    clean: !options.watch, // only clean once when not watching
    minify: !options.watch,
    globalName: 'taichunmin.crc',
    entry: ['lib/index.ts'],
  },
  ..._.map([
    'crc8',
    'crc8autosar',
    'crc8bluetooth',
    'crc8cardx',
    'crc8cdma2000',
    'crc8darc',
    'crc8dvbs2',
    'crc8ebu',
    'crc8gsma',
    'crc8gsmb',
    'crc8hitag',
    'crc8icode',
    'crc8itu',
    'crc8legic',
    'crc8mad',
    'crc8maxim',
    'crc8nrsc5',
    'crc8opensafety',
    'crc8rohc',
    'crc8saej1850',
    'crc8wcdma',
    'crc16a',
    'crc16arc',
    'crc16augccitt',
    'crc16buypass',
    'crc16ccittfalse',
    'crc16cdma2000',
    'crc16cms',
    'crc16dds110',
    'crc16dectr',
    'crc16dectx',
    'crc16dnp',
    'crc16en13757',
    'crc16genibus',
    'crc16gsm',
    'crc16iclass',
    'crc16kermit',
    'crc16lj1200',
    'crc16m17',
    'crc16maxim',
    'crc16mcrf4xx',
    'crc16modbus',
    'crc16nrsc5',
    'crc16opensafetya',
    'crc16opensafetyb',
    'crc16philips',
    'crc16profibus',
    'crc16riello',
    'crc16t10dif',
    'crc16teledisk',
    'crc16tms37157',
    'crc16usb',
    'crc16x25',
    'crc16xmodem',
    'crc32',
    'crc32autosar',
    'crc32bzip2',
    'crc32c',
    'crc32cdromedc',
    'crc32d',
    'crc32jamcrc',
    'crc32mef',
    'crc32mpeg2',
    'crc32posix',
    'crc32q',
    'crc32sata',
    'crc32xfer',
    'genericCrc8',
    'genericCrc16',
    'genericCrc32',
  ], filename => ({
    ...sharedConfig,
    splitting: true, // fix cjsInterop bug: https://github.com/egoist/tsup/issues/572
    minify: !options.watch,
    globalName: `taichunmin.crc.${filename}`,
    entry: [`lib/${filename}.ts`],
  })),
])
